# Database Configuration
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/ordering_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:BIT2AEVE@2026@2026}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Port Configuration
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your_super_secret_key_change_this_in_production
jwt.expiration=86400000
